name: CI-CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend_flask:
    name: Backend (Flask) - CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:

          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8 pytest

      - name: Lint Python code
        run: |
          if [ -f .flake8 ] || [ -f setup.cfg ] || [ -f tox.ini ] || [ -f .pep8 ]; then
            flake8 .
          else
            echo "No lint configuration found, skipping linting."
          fi

      - name: Run Python tests
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests found, skipping tests."
          fi

  deploy:
    name: Build & Push Docker Image - CD
    runs-on: ubuntu-latest
    needs: backend_flask
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        run: |
          echo "${DOCKERHUB_ACCESS_TOKEN}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build Docker Image
        run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/backend_flask:latest" .

      - name: Push Docker Image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/backend_flask:latest"

